### PR TITLE
Reusable components

### LINKED ISSUE #1: Create Custom Widget for Repeated TextField Code
**Issue Description:**
In our codebase, we've noticed that there are multiple instances where TextField widgets are used with similar configurations and properties. This repetition not only makes the code less maintainable but also increases the chances of inconsistencies and bugs. To improve code organization and reduce redundancy, we should create a custom widget that encapsulates the common TextField configurations.

P**roposed Solution:**
We propose creating a custom TextField widget that allows us to set common properties like input decoration, controller, validator, and more in a single place. This custom widget will simplify the code, improve consistency, and make it easier to maintain.

**Benefits:**

- Improved code readability and maintainability.
- Reduced code duplication and potential bugs.
- Enhanced consistency in the UI.

### PR DESCRIPTION
**Pull request by as3hr**
I have added a widget named "Custom TextField" which takes in required params and performs the action, I have also performed testing, and It is working fine.
I made the account myself and also tried signing in and it is working fine.

I have also removed unusable code and commented out print statements to remove warnings from the project and made it look more cleaner.

fixed #1

### CODE REVIEW

**Comment by cynthiakonar** [comment]
The code looks good! 
Can you please add a screenshot of the CustomTextField screen? @as3hr

**Comment by as3hr** [comment]
Sure @cynthiakonar, here you go:

ss1

ss2

ss3

ss4

ss5

**Comment by as3hr** [comment]
One thing, we can also add in this is, that we can add the functionality of obSecure text, currently the password field has the obsecure option, but we can also have a suffix icon at the end by which we can trigeer the obsecure boolean, the user will then be able to see the password to and also hide it.

you can create a new issue and I'll be happy to contribute to that one also if its okay for you🙌

**Comment by cynthiakonar** [comment]
Obscure text is not required as of now, this much looks good. 
Thank you for contributing. Happy Hacktoberfest!

**Pull request merged**
